name: GitHub Auto Tag - Test
run-name: ${{ github.actor }} Auto tag v2
on: [push]
jobs:
  Explore-GitHub-Actions:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Get next versionc
        uses: reecetech/version-increment@2023.9.3
        id: version
        with:
          use_api: true
          increment: patch
          release_branch: main