name: GitHub Auto Tag - Test
run-name: ${{ github.actor }} Auto tag v2
on: [push]
jobs:
  Explore-GitHub-Actions:
     if: true
     runs-on: ubuntu-latest
     outputs:
       NAME: "Explore-GitHub-Actions"
     steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Get next version
        uses: reecetech/version-increment@2023.10.1
        id: version
        with:
          use_api: true
          increment: patch
          release_branch: main
  Job2:
    if: ${{ !success() }}
    #if: false
    outputs:
       NAME: "Job2"
    needs: Explore-GitHub-Actions
    runs-on: ubuntu-latest
    steps:
      - run: echo Helloooo from Job2 .....

  create-tag:
    if: ${{ always() && (needs.Explore-GitHub-Actions.outputs.NAME || needs.Job2.outputs.NAME) }}
    name: Tag Branch
    runs-on: ubuntu-latest
    needs: [Explore-GitHub-Actions,Job2]
    steps:
      - env:
          JOB1: ${{needs.Explore-GitHub-Actions.outputs.NAME}}
          JOB2: ${{needs.Job2.outputs.NAME}}
        run: echo "Helloooo from Job2 ($JOB1) ($JOB2)....."
