name: GitHub Auto Tag - Test
run-name: ${{ github.actor }} Auto tag
on: [push]
jobs:
  Explore-GitHub-Actions:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Get next version
        uses: reecetech/version-increment@2023.9.3
        id: version
        with:
          scheme: semver
          increment: patch