name: GitHub Auto Tag - Test
run-name: ${{ github.actor }} Auto tag v2
on: [push]
jobs:
  Explore-GitHub-Actions:
     if: false
     runs-on: ubuntu-latest
     steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Get next version
        uses: reecetech/version-increment@2023.10.1
        id: version
        with:
          use_api: true
          increment: patch
          release_branch: main
  Job2:
    if: ${{ !success() }}
    needs: Explore-GitHub-Actions
    runs-on: ubuntu-latest
    steps:
      - run: echo Helloooo from Job2 .....
